[versions]
# libraries
assertj = "3.27.3" # https://mvnrepository.com/artifact/org.assertj/assertj-core
junit = "5.13.4" # https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api

# plugins
kotlin = "2.2.10" # https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
changelog = "2.4.0" # https://github.com/JetBrains/gradle-changelog-plugin
intelliJPlatform = "2.7.2" # https://github.com/JetBrains/intellij-platform-gradle-plugin
pythonPlugin = "2.9.0" # https://github.com/PrzemyslawSwiderski/python-gradle-plugin

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterPlatform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pythonPlugin = { id = "com.pswidersk.python-plugin", version.ref = "pythonPlugin" }
