[versions]
# libraries
assertj = "3.27.6" # https://mvnrepository.com/artifact/org.assertj/assertj-core
junit = "6.0.1" # https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
mockito = "5.21.0"

# plugins
kotlin = "2.2.21" # https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
changelog = "2.5.0" # https://github.com/JetBrains/gradle-changelog-plugin
intelliJPlatform = "2.10.5" # https://github.com/JetBrains/intellij-platform-gradle-plugin
pythonPlugin = "3.1.4" # https://github.com/PrzemyslawSwiderski/python-gradle-plugin

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
jupiterPlatform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pythonPlugin = { id = "com.pswidersk.python-plugin", version.ref = "pythonPlugin" }

[bundles]
test = ["assertj", "jupiterApi", "jupiterParams", "jupiterPlatform", "mockito"]